services:
  - type: web
    name: agri-link-backend
    env: python
    rootDir: agri-link-backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: DB_PATH
        # Quick fix: uses a writable, non-persistent path so deploy succeeds immediately.
        value: /tmp/app.db
      - key: ALLOWED_ORIGINS
        # Replace with your deployed frontend domains, comma-separated.
        value: https://your-frontend.vercel.app
    # Uncomment this block to use a persistent SQLite database on a disk.
    # disks:
    #   - name: data
    #     mountPath: /var/data
    #     sizeGB: 1
    #     # If you enable the disk above, also change DB_PATH to /var/data/app.db
