"""create collaborations and participations tables

Revision ID: 2f9badeecdc6
Revises: 974e2a16a34e
Create Date: 2025-10-24 01:28:49.079992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f9badeecdc6'
down_revision = '974e2a16a34e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collaborations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=20), nullable=False),
    sa.Column('location', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_table('collaboration_crops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collaboration_id', sa.Integer(), nullable=False),
    sa.Column('crop_name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('weight_demand', sa.Float(), nullable=False),
    sa.Column('contributed_weight', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['collaboration_id'], ['collaborations.id'], name=op.f('fk_collaboration_crops_collaboration_id_collaborations')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collaboration_participations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collaboration_id', sa.Integer(), nullable=False),
    sa.Column('farmer_name', sa.String(length=100), nullable=False),
    sa.Column('weight_contributed', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['collaboration_id'], ['collaborations.id'], name=op.f('fk_collaboration_participations_collaboration_id_collaborations')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collaboration_participations')
    op.drop_table('collaboration_crops')
    op.drop_table('collaborations')
    # ### end Alembic commands ###
