"""Upgraded buyers table to add phone number column

Revision ID: 35ff16d7785c
Revises: 1ff5781af845
Create Date: 2025-10-24 12:13:36.955339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35ff16d7785c'
down_revision = '1ff5781af845'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buyers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buyers', schema=None) as batch_op:
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
