"""Initial migration

Revision ID: 8ae334f5b9c0
Revises: 
Create Date: 2025-10-24 23:11:38.838220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ae334f5b9c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buyers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(length=10), nullable=True),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('collaborations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=20), nullable=False),
    sa.Column('location', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_table('farmers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(length=10), nullable=True),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('collaboration_crops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collaboration_id', sa.Integer(), nullable=False),
    sa.Column('crop_name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('weight_demand', sa.Float(), nullable=False),
    sa.Column('contributed_weight', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['collaboration_id'], ['collaborations.id'], name=op.f('fk_collaboration_crops_collaboration_id_collaborations')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collaboration_participations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collaboration_id', sa.Integer(), nullable=False),
    sa.Column('farmer_name', sa.String(length=100), nullable=False),
    sa.Column('weight_contributed', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['collaboration_id'], ['collaborations.id'], name=op.f('fk_collaboration_participations_collaboration_id_collaborations')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.Enum('Cereals', 'Vegetables', 'Fruits', 'Export Crop', 'Other', name='crop_categories'), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], name=op.f('fk_crops_farmer_id_farmers')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('crop_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('post_harvest_period', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], name=op.f('fk_offers_crop_id_crops')),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], name=op.f('fk_offers_farmer_id_farmers')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offers')
    op.drop_table('crops')
    op.drop_table('collaboration_participations')
    op.drop_table('collaboration_crops')
    op.drop_table('farmers')
    op.drop_table('collaborations')
    op.drop_table('buyers')
    # ### end Alembic commands ###
