"""Add crop_id to participation

Revision ID: 8ef6850926cc
Revises: 8ae334f5b9c0
Create Date: 2025-10-25 09:04:27.419088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ef6850926cc'
down_revision = '8ae334f5b9c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collaboration_participations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('crop_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_collaboration_participations_crop_id_collaboration_crops'), 'collaboration_crops', ['crop_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collaboration_participations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_collaboration_participations_crop_id_collaboration_crops'), type_='foreignkey')
        batch_op.drop_column('crop_id')

    # ### end Alembic commands ###
