"""create farmers, crops, offers tables

Revision ID: 974e2a16a34e
Revises: 
Create Date: 2025-10-23 20:12:31.088877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '974e2a16a34e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farmers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.Enum('Cereals', 'Vegetables', 'Fruits', 'Export Crop', 'Other', name='crop_categories'), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], name=op.f('fk_crops_farmer_id_farmers')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('crop_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('post_harvest_period', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], name=op.f('fk_offers_crop_id_crops')),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], name=op.f('fk_offers_farmer_id_farmers')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offers')
    op.drop_table('crops')
    op.drop_table('farmers')
    # ### end Alembic commands ###
